remote_theme: "mmistakes/minimal-mistakes@4.26.2"

header:
  image: /assets/img/header.jpg

title: Edward Tang
name: Edward Tang
description: "Edward Tang's Portfolio"
logo: /assets/img/logo.png
masthead_title: " "
breadcrumbs: true

include: 
  - _pages

atom_feed:
  hide: true

author:
  name: "Edward Tang"
  avatar: /assets/img/IMG_300.png
  bio: "A data scientist who loves snowboarding, nature, books, searching for meaning in life..."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/edward330176"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/edward-tang-m-s-66a941201/"
    - label: "Medium"
      icon: "fa-brands fa-medium"
      url: "https://medium.com/@edwardlongtang"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
